ACTORS: list[dict] = [
    # ── Telugu actors ─────────────────────────────────────────────────────────
    {"name": "Mahesh Babu",        "db_name": "Mahesh Babu",          "handle": "urstrulyMahesh",    "industry": "Telugu"},
    {"name": "Allu Arjun",         "db_name": "Allu Arjun",           "handle": "alluarjun",         "industry": "Telugu"},
    {"name": "Jr. NTR",            "db_name": "Jr. NTR",              "handle": "tarak9999",         "industry": "Telugu"},
    {"name": "Ram Charan",         "db_name": "Ram Charan",           "handle": "AlwaysRamCharan",   "industry": "Telugu"},
    {"name": "Pawan Kalyan",       "db_name": "Pawan Kalyan",         "handle": "PawanKalyan",       "industry": "Telugu"},
    {"name": "Vijay Deverakonda",  "db_name": "Vijay Deverakonda",    "handle": "TheDeverakonda",    "industry": "Telugu"},
    {"name": "Nani",               "db_name": "Nani",                 "handle": "NameisNani",        "industry": "Telugu"},
    {"name": "Nagarjuna",          "db_name": "Nagarjuna Akkineni",   "handle": "iamnagarjuna",      "industry": "Telugu"},
    {"name": "Chiranjeevi",        "db_name": "Chiranjeevi",          "handle": "KChiruTweets",      "industry": "Telugu"},
    {"name": "Rana Daggubati",     "db_name": "Rana Daggubati",       "handle": "RanaDaggubati",     "industry": "Telugu"},
    {"name": "Ravi Teja",          "db_name": "Ravi Teja",            "handle": "RaviTeja_offl",     "industry": "Telugu"},
    {"name": "Naga Chaitanya",     "db_name": "Naga Chaitanya",       "handle": "chay_akkineni",     "industry": "Telugu"},
    {"name": "Sharwanand",         "db_name": "Sharwanand",           "handle": "ImSharwanand",      "industry": "Telugu"},
    {"name": "Kalyan Ram",         "db_name": "Kalyan Ram",           "handle": "NANDAMURIKALYAN",   "industry": "Telugu"},
    {"name": "Venkatesh",          "db_name": "Venkatesh Daggubati",  "handle": "VenkyMama",         "industry": "Telugu"},
    {"name": "Samantha",           "db_name": "Samantha",             "handle": "Samanthaprabhu2",   "industry": "Telugu"},
    {"name": "Pooja Hegde",        "db_name": "Pooja Hegde",          "handle": "hegdepooja",        "industry": "Telugu"},
    {"name": "Rashmika Mandanna",  "db_name": "Rashmika Mandanna",    "handle": "iamRashmika",       "industry": "Telugu"},
    {"name": "Ram Pothineni",      "db_name": "Ram Pothineni",        "handle": "ramsayz",           "industry": "Telugu"},
    {"name": "Akhil Akkineni",     "db_name": "Akhil Akkineni",       "handle": "AkhilAkkineni8",    "industry": "Telugu"},
    {"name": "Sai Dharam Tej",     "db_name": "Sai Dharam Tej",       "handle": "IamSaiDharamTej",   "industry": "Telugu"},
    {"name": "Allu Sirish",        "db_name": "Allu Sirish",          "handle": "AlluSirish",        "industry": "Telugu"},
    {"name": "Manoj Manchu",       "db_name": "Manoj Manchu",         "handle": "HeroManoj1",        "industry": "Telugu"},
    {"name": "Nikhil Siddhartha", "db_name": "Nikhil Siddhartha",    "handle": "actor_Nikhil",      "industry": "Telugu"},
    {"name": "Naveen Polishetty",  "db_name": "Naveen Polishetty",    "handle": "NaveenPolishety",   "industry": "Telugu"},
    {"name": "VishwakSen",         "db_name": "VishwakSen",           "handle": "VishwakSenActor",   "industry": "Telugu"},
    {"name": "Naga Shaurya",       "db_name": "Naga Shaurya",         "handle": "IamNagashaurya",    "industry": "Telugu"},
    {"name": "Priyadarshi",        "db_name": "Priyadarshi",          "handle": "Preyadarshe",       "industry": "Telugu"},
    {"name": "Kiran Abbavaram",    "db_name": "Kiran Abbavaram",      "handle": "Kiran_Abbavaram",   "industry": "Telugu"},
    {"name": "Rahul Ramakrishna",  "db_name": "Rahul Ramakrishna",    "handle": "eyrahul",           "industry": "Telugu"},
    {"name": "Naveen Chandra",     "db_name": "Naveen Chandra",       "handle": "Naveenc212",        "industry": "Telugu"},
    {"name": "Kajal Aggarwal",     "db_name": "Kajal Aggarwal",       "handle": "MsKajalAggarwal",   "industry": "Telugu"},
    {"name": "Jagapathi Babu",     "db_name": "Jagapathi Babu",       "handle": "IamJagguBhai",      "industry": "Telugu"},
    {"name": "SS Karthikeya",      "db_name": "SS Karthikeya",        "handle": "ssk1122",           "industry": "Telugu"},
    {"name": "Sridevi Sreedhar",   "db_name": "Sridevi Sreedhar",     "handle": "sridevisreedhar",   "industry": "Telugu"},
    {"name": "Karthik Ravivarma",  "db_name": "Karthik Ravivarma",    "handle": "Karthikravivarm",   "industry": "Telugu"},
    {"name": "Gulshan Devaiah",    "db_name": "Gulshan Devaiah",      "handle": "gulshandevaiah",    "industry": "Telugu"},
    # ── Tamil actors ─────────────────────────────────────────────────────────
    {"name": "Kamal Haasan",       "db_name": "Kamal Haasan",         "handle": "ikamalhaasan",      "industry": "Tamil"},
    {"name": "Vijay",              "db_name": "Vijay",                "handle": "actorvijay",        "industry": "Tamil"},
    {"name": "Rajinikanth",        "db_name": "Rajinikanth",          "handle": "rajinikanth",       "industry": "Tamil"},
    {"name": "Dhanush",            "db_name": "Dhanush",              "handle": "dhanushkraja",      "industry": "Tamil"},
    {"name": "Suriya",             "db_name": "Suriya",               "handle": "Suriya_offl",       "industry": "Tamil"},
    {"name": "Sivakarthikeyan",    "db_name": "Sivakarthikeyan",      "handle": "Siva_Kartikeyan",   "industry": "Tamil"},
    {"name": "Silambarasan",       "db_name": "Silambarasan",         "handle": "SilambarasanTR_",   "industry": "Tamil"},
    {"name": "Vikram",             "db_name": "Vikram",               "handle": "chiyaan",           "industry": "Tamil"},
    {"name": "Vijay Sethupathi",   "db_name": "Vijay Sethupathi",     "handle": "VijaySethuOffl",    "industry": "Tamil"},
    {"name": "R. Madhavan",        "db_name": "R. Madhavan",          "handle": "ActorMadhavan",     "industry": "Tamil"},
    {"name": "Nayanthara",         "db_name": "Nayanthara",           "handle": "NayantharaU",       "industry": "Tamil"},
    {"name": "Karthi",             "db_name": "Karthi",               "handle": "Karthi_Offl",       "industry": "Tamil"},
    {"name": "GV Prakash Kumar",   "db_name": "GV Prakash Kumar",     "handle": "gvprakash",         "industry": "Tamil"},
    {"name": "Ravi Mohan",         "db_name": "Ravi Mohan",           "handle": "iam_RaviMohan",     "industry": "Tamil"},
    {"name": "SJ Suryah",          "db_name": "SJ Suryah",            "handle": "iam_SJSuryah",      "industry": "Tamil"},
    {"name": "Santhanam",          "db_name": "Santhanam",            "handle": "iamsanthanam",      "industry": "Tamil"},
    {"name": "Nivetha Thomas",     "db_name": "Nivetha Thomas",       "handle": "i_nivethathomas",   "industry": "Tamil"},
    {"name": "Vishal",             "db_name": "Vishal",               "handle": "VishalKOfficial",   "industry": "Tamil"},
    {"name": "Kathir",             "db_name": "Kathir",               "handle": "am_kathir",         "industry": "Tamil"},
    {"name": "Anjali",             "db_name": "Anjali",               "handle": "yoursanjali",       "industry": "Tamil"},
    {"name": "Pradeep Ranganathan","db_name": "Pradeep Ranganathan",  "handle": "pradeeponelife",    "industry": "Tamil"},
    {"name": "Atharvaa",           "db_name": "Atharvaa",             "handle": "Atharvaamurali",    "industry": "Tamil"},
    {"name": "Vijayantony",        "db_name": "Vijayantony",          "handle": "vijayantony",       "industry": "Tamil"},
    {"name": "Arjun Das",          "db_name": "Arjun Das",            "handle": "iam_arjundas",      "industry": "Tamil"},
    {"name": "Yogi Babu",          "db_name": "Yogi Babu",            "handle": "iYogiBabu",         "industry": "Tamil"},
    {"name": "Malavika Mohanan",   "db_name": "Malavika Mohanan",     "handle": "MalavikaM_",        "industry": "Tamil"},
    {"name": "Trisha Krishnan",    "db_name": "Trisha Krishnan",      "handle": "trishtrashers",     "industry": "Tamil"},
    {"name": "Keerthy Suresh",     "db_name": "Keerthy Suresh",       "handle": "KeerthyOfficial",   "industry": "Tamil"},
    {"name": "Vikram Prabhu",      "db_name": "Vikram Prabhu",        "handle": "iamVikramPrabhu",   "industry": "Tamil"},
    {"name": "Sunainaa",           "db_name": "Sunainaa",             "handle": "TheSunainaa",       "industry": "Tamil"},
    {"name": "Athulyaa Ravi",      "db_name": "Athulyaa Ravi",        "handle": "AthulyaOfficial",   "industry": "Tamil"},
    {"name": "Master Mahendran",   "db_name": "Master Mahendran",     "handle": "Actor_Mahendran",   "industry": "Tamil"},
    # ── Malayalam actors ──────────────────────────────────────────────────────
    {"name": "Mohanlal",           "db_name": "Mohanlal",             "handle": "Mohanlal",          "industry": "Malayalam"},
    {"name": "Mammootty",          "db_name": "Mammootty",            "handle": "mammukka",          "industry": "Malayalam"},
    {"name": "Dulquer Salmaan",    "db_name": "Dulquer Salmaan",      "handle": "dulQuer",           "industry": "Malayalam"},
    {"name": "Prithviraj",         "db_name": "Prithviraj Sukumaran", "handle": "PrithviOfficial",   "industry": "Malayalam"},
    {"name": "Tovino Thomas",      "db_name": "Tovino Thomas",        "handle": "ttovino",           "industry": "Malayalam"},
    {"name": "Nivin Pauly",        "db_name": "Nivin Pauly",          "handle": "NivinOfficial",     "industry": "Malayalam"},
    {"name": "Unni Mukundan",      "db_name": "Unni Mukundan",        "handle": "Iamunnimukundan",   "industry": "Malayalam"},
    {"name": "Parvathy",           "db_name": "Parvathy",             "handle": "paro_nair",         "industry": "Malayalam"},
    {"name": "Jagadish",           "db_name": "Jagadish",             "handle": "Jagadishbliss",     "industry": "Malayalam"},
    {"name": "Samyuktha",          "db_name": "Samyuktha",            "handle": "iamsamyuktha_",     "industry": "Malayalam"},
    # ── Kannada actors ────────────────────────────────────────────────────────
    {"name": "Yash",               "db_name": "Yash",                 "handle": "TheNameIsYash",     "industry": "Kannada"},
    {"name": "Sudeep",             "db_name": "Sudeepa",              "handle": "KicchaSudeep",      "industry": "Kannada"},
    {"name": "Upendra",            "db_name": "Upendra",              "handle": "nimmaupendra",      "industry": "Kannada"},
    {"name": "Darshan",            "db_name": "Darshan",              "handle": "dasadarshan",       "industry": "Kannada"},
    {"name": "Rakshit Shetty",     "db_name": "Rakshit Shetty",       "handle": "rakshitshetty",     "industry": "Kannada"},
    {"name": "Shiva Rajkumar",     "db_name": "Shiva Rajkumar",       "handle": "NimmaShivanna",     "industry": "Kannada"},
    {"name": "Srinidhi Shetty",    "db_name": "Srinidhi Shetty",      "handle": "SrinidhiShetty7",   "industry": "Kannada"},
    {"name": "Shanvi Srivastava",  "db_name": "Shanvi Srivastava",    "handle": "shanvisrivastav",   "industry": "Kannada"},
    {"name": "Dhruva Sarja",       "db_name": "Dhruva Sarja",         "handle": "DhruvaSarja",       "industry": "Kannada"},
    {"name": "SriiMurali",         "db_name": "SriiMurali",           "handle": "SRIMURALIII",       "industry": "Kannada"},
    {"name": "Yuva Rajkumar",      "db_name": "Yuva Rajkumar",        "handle": "yuva_rajkumar",     "industry": "Kannada"},
    {"name": "Darling Krishna",    "db_name": "Darling Krishna",      "handle": "darlingkrishnaa",   "industry": "Kannada"},
    {"name": "Rachita Ram",        "db_name": "Rachita Ram",          "handle": "RachitaRamDQ",      "industry": "Kannada"},
    {"name": "Amulya",             "db_name": "Amulya",               "handle": "nimmaamulya",       "industry": "Kannada"},
]

# Tier 2 — signal accounts (directors, composers, studios, trade analysts, media).
# When these accounts tweet mentioning an actor, we find that actor's recent tweet
# and reply to IT (never to the signal account directly).
SIGNAL_ACCOUNTS: list[dict] = [
    # ── Directors — Telugu ────────────────────────────────────────────────────
    {"name": "SS Rajamouli",         "handle": "ssrajamouli",      "role": "director"},
    {"name": "Sukumar",              "handle": "SukumarWritings",  "role": "director"},
    {"name": "Trivikram Srinivas",   "handle": "trivikram_s",      "role": "director"},
    {"name": "Sandeep Reddy Vanga",  "handle": "imvangasandeep",   "role": "director"},
    {"name": "Nag Ashwin",           "handle": "nagashwin7",       "role": "director"},
    {"name": "Director Maruthi",     "handle": "DirectorMaruthi",  "role": "director"},
    {"name": "Prasanth Varma",       "handle": "PrasanthVarma",    "role": "director"},
    {"name": "Vijay Kanakamedala",   "handle": "DirVijayK",        "role": "director"},
    # ── Directors — Tamil ─────────────────────────────────────────────────────
    {"name": "Shankar",              "handle": "shankarshanmugh",  "role": "director"},
    {"name": "Lokesh Kanagaraj",     "handle": "Dir_Lokesh",       "role": "director"},
    {"name": "Vignesh Shivan",       "handle": "VigneshShivN",     "role": "director"},
    {"name": "Atlee",                "handle": "Atlee_dir",        "role": "director"},
    {"name": "Karthik Subbaraj",     "handle": "karthiksubbaraj",  "role": "director"},
    {"name": "Selvaraghavan",        "handle": "selvaraghavan",    "role": "director"},
    {"name": "Gautham Vasudev Menon","handle": "menongautham",     "role": "director"},
    {"name": "Nelson Dilipkumar",    "handle": "Nelsondilpkumar",  "role": "director"},
    # ── Directors — Malayalam ─────────────────────────────────────────────────
    {"name": "Priyadarshan",         "handle": "priyadarshan_i",   "role": "director"},
    {"name": "Rahi Anil Barve",      "handle": "BarveRahi",        "role": "director"},
    # ── Directors — Kannada ───────────────────────────────────────────────────
    {"name": "Pavan Wadeyar",        "handle": "PavanWadeyar",     "role": "director"},
    {"name": "Tharun Sudhir",        "handle": "TharunSudhir",     "role": "director"},
    {"name": "Yogaraj Bhat",         "handle": "YogarajBhat",      "role": "director"},
    # ── Composers ─────────────────────────────────────────────────────────────
    {"name": "AR Rahman",            "handle": "arrahman",         "role": "composer"},
    {"name": "Anirudh Ravichander",  "handle": "anirudhofficial",  "role": "composer"},
    {"name": "Thaman S",             "handle": "MusicThaman",      "role": "composer"},
    {"name": "Devi Sri Prasad",      "handle": "ThisIsDSP",        "role": "composer"},
    {"name": "MM Keeravani",         "handle": "mmkeeravaani",     "role": "composer"},
    {"name": "Yuvan Shankar Raja",   "handle": "thisisysr",        "role": "composer"},
    {"name": "Ravi Basrur",          "handle": "RaviBasrur",       "role": "composer"},
    {"name": "Vasuki Vaibhav",       "handle": "vasukivaibhav",    "role": "composer"},
    # ── Producers / Studios — Telugu ─────────────────────────────────────────
    {"name": "Mythri Movie Makers",  "handle": "MythriOfficial",   "role": "studio"},
    {"name": "Haarika & Hassine",    "handle": "haarikahassine",   "role": "studio"},
    {"name": "Vyjayanthi Movies",    "handle": "VyjayanthiFilms",  "role": "studio"},
    {"name": "Sithara Entertainments","handle": "SitharaEnts",     "role": "studio"},
    {"name": "DVV Entertainment",    "handle": "DVVMovies",         "role": "studio"},
    {"name": "UV Creations",         "handle": "UV_Creations",     "role": "studio"},
    {"name": "Geetha Arts",          "handle": "GeethaArts",       "role": "studio"},
    {"name": "Naga Vamsi",           "handle": "vamsi84",          "role": "studio"},
    {"name": "Dwaraka Creations",    "handle": "dwarakacreation",  "role": "studio"},
    {"name": "SK Productions",       "handle": "SKProdOffl",       "role": "studio"},
    # ── Producers / Studios — Tamil ───────────────────────────────────────────
    {"name": "Sun Pictures",         "handle": "sunpictures",      "role": "studio"},
    {"name": "Lyca Productions",     "handle": "LycaProductions",  "role": "studio"},
    {"name": "Red Giant Movies",     "handle": "RedGiantMovies_",  "role": "studio"},
    {"name": "AGS Entertainment",    "handle": "Ags_production",   "role": "studio"},
    {"name": "Seven Screen Studio",  "handle": "7screenstudio",    "role": "studio"},
    {"name": "PRK Productions",      "handle": "PRK_Productions",  "role": "studio"},
    {"name": "Vels Film Intl",       "handle": "VelsFilmIntl",     "role": "studio"},
    {"name": "A2 Studio",            "handle": "a2studoffl",       "role": "studio"},
    {"name": "V Creations (Thanu)",  "handle": "theVcreations",    "role": "studio"},
    {"name": "Archana Kalpathi",     "handle": "archanakalpathi",  "role": "studio"},
    # ── Producers / Studios — Malayalam ──────────────────────────────────────
    {"name": "SreeGokulam Movies",   "handle": "GokulamMovies",    "role": "studio"},
    {"name": "Ahimsa Entertainment", "handle": "ahimsafilms",      "role": "studio"},
    # ── Producers / Studios — Kannada ────────────────────────────────────────
    {"name": "Hombale Films",        "handle": "hombalefilms",     "role": "studio"},
    {"name": "Hombale Group",        "handle": "HombaleGroup",     "role": "studio"},
    {"name": "SVCC",                 "handle": "SVCCofficial",     "role": "studio"},
    # ── Trade analysts — pan-India ────────────────────────────────────────────
    {"name": "Taran Adarsh",         "handle": "taran_adarsh",     "role": "trade"},
    {"name": "Box Office India",     "handle": "Box_Off_India",    "role": "trade"},
    {"name": "Sacnilk Entertainment","handle": "SacnilkEntmt",     "role": "trade"},
    {"name": "Cinetrak",             "handle": "Cinetrak",         "role": "trade"},
    {"name": "Anupama Chopra",       "handle": "anupamachopra",    "role": "trade"},
    # ── Trade analysts — Telugu ───────────────────────────────────────────────
    {"name": "Track Tollywood",      "handle": "TrackTwood",       "role": "trade"},
    {"name": "TBO Updates",          "handle": "TBO_Updates",      "role": "trade"},
    {"name": "Andhra Box Office",    "handle": "AndhraBoxOffice",  "role": "trade"},
    {"name": "News Box Office",      "handle": "NEWS_BOXOFFICE",   "role": "trade"},
    {"name": "idlebrain jeevi",      "handle": "idlebrainjeevi",   "role": "trade"},
    {"name": "Incognito Telugu",     "handle": "IncognitoTelugu",  "role": "trade"},
    # ── Trade analysts — Tamil ────────────────────────────────────────────────
    {"name": "Ramesh Bala",          "handle": "rameshlaus",       "role": "trade"},
    {"name": "Sreedhar Pillai",      "handle": "sri50",            "role": "trade"},
    {"name": "Kaushik LM",           "handle": "LMKMovieManiac",   "role": "trade"},
    {"name": "Box Office South",     "handle": "BoxOfficeSouth2",  "role": "trade"},
    {"name": "Behindwoods",          "handle": "behindwoods",      "role": "trade"},
    {"name": "Lets Cinema",          "handle": "letscinema",       "role": "trade"},
    {"name": "Kollywood Talks",      "handle": "kollywoodtalks",   "role": "trade"},
    {"name": "Rajasekar",            "handle": "sekartweets",      "role": "trade"},
    {"name": "Aakashavaani",         "handle": "TheAakashavaani",  "role": "trade"},
    {"name": "Laxmi Kanth",          "handle": "iammoviebuff007",  "role": "trade"},
    {"name": "Trendswood",           "handle": "Trendswoodcom",    "role": "trade"},
    {"name": "The Art Of Dialogue",  "handle": "ArtOfDialogue_",   "role": "trade"},
    {"name": "Movie Tamil",          "handle": "_MovieTamil",      "role": "trade"},
    {"name": "Thyview",              "handle": "Thyview",          "role": "trade"},
    # ── Trade analysts — Malayalam ────────────────────────────────────────────
    {"name": "Jerin Georgekutty",    "handle": "jerinGeorgekut2",  "role": "trade"},
    {"name": "AB George",            "handle": "AbGeorge_",        "role": "trade"},
    {"name": "Mollywood BO",         "handle": "MollywoodBo1",     "role": "trade"},
    {"name": "MalayalamReview",      "handle": "MalayalamReview",  "role": "trade"},
    {"name": "Forum Kerala",         "handle": "Forumkeralam2",    "role": "trade"},
    {"name": "Kerala Box Office",    "handle": "KeralaBxOffce",    "role": "trade"},
    {"name": "Raunaq Mangottil",     "handle": "RaunaqMangottil",  "role": "trade"},
    {"name": "Sajin Shrijith",       "handle": "SajinShrijith",    "role": "trade"},
    {"name": "Avinash Ramachandran", "handle": "Avinash_R13",      "role": "trade"},
    # ── Trade analysts — Kannada ──────────────────────────────────────────────
    {"name": "Kannada BO",           "handle": "KANNADA__BO",      "role": "trade"},
    {"name": "Sandalwood Box O",     "handle": "SandalwoodBoxO1",  "role": "trade"},
    {"name": "KA Talkies",           "handle": "KA_Talkies",       "role": "trade"},
    # ── Critics / Media ───────────────────────────────────────────────────────
    {"name": "Baradwaj Rangan",      "handle": "baradwajrangan",   "role": "critic"},
    {"name": "Film Companion South", "handle": "FCompanionSouth",  "role": "critic"},
    {"name": "Manobala V",           "handle": "ManobalaV",        "role": "critic"},
    {"name": "Ram Venkat Srikar",    "handle": "RamVenkatSrikar",  "role": "critic"},
    {"name": "CinemaWithAB",         "handle": "CinemaWithAB",     "role": "critic"},
    {"name": "South Indian BO",      "handle": "BOSouthIndian",    "role": "trade"},
    {"name": "The Route",            "handle": "TheRoute",         "role": "critic"},
    {"name": "Venky Reviews",        "handle": "venkyreviews",     "role": "critic"},
    {"name": "Venkatramanan",        "handle": "VenkatRamanan_",   "role": "critic"},
    {"name": "Sudhir Srinivasan",    "handle": "sudhirsrinivasn",  "role": "critic"},
    {"name": "Nishit Shaw",          "handle": "NishitShawHere",   "role": "critic"},
    {"name": "Sukanya Verma",        "handle": "SukanyaVerma",     "role": "critic"},
    {"name": "Rahul Desai",          "handle": "ReelReptile",      "role": "critic"},
    {"name": "Vishal Menon",         "handle": "Vishal1Menon",     "role": "critic"},
    {"name": "ANMOL JAMWAL",         "handle": "jammypants4",      "role": "critic"},
    {"name": "Amrutha Iyengar",      "handle": "amrutha_iyengar",  "role": "critic"},
    {"name": "Shreya Dhanwanthary",  "handle": "shreyadhan13",     "role": "critic"},
    {"name": "Shreemi Verma",        "handle": "shreemiverma19",   "role": "critic"},
    {"name": "Rahul Raut",           "handle": "Rahulrautwrites",  "role": "critic"},
    {"name": "Simply South",         "handle": "SimplySouthApp",   "role": "critic"},
    {"name": "Wall Poster Cinema",   "handle": "walpostercinema",  "role": "critic"},
    {"name": "CinemaRare",           "handle": "CinemaRareIN",     "role": "critic"},
    {"name": "Jeya Suriya",          "handle": "MSPMovieManiac",   "role": "critic"},
    {"name": "Mouli Talks",          "handle": "Mouli_Talks",      "role": "critic"},
    {"name": "Ayyappan",             "handle": "Ayyappan_1504",    "role": "critic"},
    {"name": "Himesh Mankad",        "handle": "HimeshMankad",     "role": "critic"},
    {"name": "Fahir Maithutty",      "handle": "fahir_me",         "role": "critic"},
    {"name": "Mohar Basu",           "handle": "MoharBasu",        "role": "critic"},
    {"name": "Aashameera Aiyappan",  "handle": "aashameera",       "role": "critic"},
    {"name": "Saloon Kada",          "handle": "saloon_kada",      "role": "critic"},
    {"name": "Sony Music South",     "handle": "SonyMusicSouth",   "role": "media"},
    {"name": "Home Screen Ent",      "handle": "homescreenent",    "role": "media"},
    # ── Directors (additional) ────────────────────────────────────────────────
    {"name": "Ram Gopal Varma",      "handle": "RGVzoomin",        "role": "director"},
    {"name": "John Mahendran",       "handle": "Johnroshan",       "role": "director"},
    {"name": "Aneesh Chaganty",      "handle": "aneeshchaganty",   "role": "director"},
    # ── Studios / Producers (additional) ─────────────────────────────────────
    {"name": "SKN",                  "handle": "SKNonline",        "role": "studio"},
    {"name": "Suneel",               "handle": "suneeltollywood",  "role": "studio"},
    {"name": "People Media Factory", "handle": "peoplemediafcy",   "role": "studio"},
    {"name": "Bhadrakali Pictures",  "handle": "VangaPictures",    "role": "studio"},
    {"name": "PEDDI",                "handle": "PeddiMovieOffl",   "role": "studio"},
    {"name": "Varanasi",             "handle": "VaranasiMovie",    "role": "studio"},
    # ── Trade (additional) ────────────────────────────────────────────────────
    {"name": "Box Office",           "handle": "Box_Office_BO",    "role": "trade"},
    {"name": "Telugu Chitraalu",     "handle": "CineChitraalu",    "role": "trade"},
    {"name": "N Anand",              "handle": "BussyAnand",       "role": "trade"},
    {"name": "sureshkamatchi",       "handle": "sureshkamatchi",   "role": "trade"},
    {"name": "Vasu Cinemas",         "handle": "vasutheatre",      "role": "trade"},
    {"name": "Star South Overseas",  "handle": "StarSouthEnt",     "role": "trade"},
    # ── Critics / Media (additional) ─────────────────────────────────────────
    {"name": "Siddarth Srinivas",    "handle": "sidhuwrites",      "role": "critic"},
    {"name": "MohitVerse",           "handle": "comicverseyt",     "role": "critic"},
    {"name": "Shazzam",              "handle": "callmeshazzam",    "role": "critic"},
    {"name": "Anayka",               "handle": "anaykashe",        "role": "media"},
    {"name": "Kavignar Thamarai",    "handle": "Kavithamarai",     "role": "media"},
    {"name": "Geetha Madhuri",       "handle": "geethasinger",     "role": "media"},
    {"name": "Devipriya",            "handle": "sairaaj44",        "role": "media"},
    # ── TV Channels ───────────────────────────────────────────────────────────
    {"name": "Vijay Television",     "handle": "vijaytelevision",  "role": "media"},
    {"name": "Sun TV",               "handle": "SunTV",            "role": "media"},
    {"name": "Gemini TV",            "handle": "GeminiTV",         "role": "media"},
    {"name": "Udaya TV",             "handle": "UdayaTV",          "role": "media"},
    {"name": "Star Maa",             "handle": "StarMaa",          "role": "media"},
    {"name": "Zee Telugu",           "handle": "ZeeTelugu",        "role": "media"},
    {"name": "Colors Kannada",       "handle": "ColorsKannada",    "role": "media"},
    {"name": "Asianet",              "handle": "asianet",          "role": "media"},
    {"name": "Mazhavil Manorama",    "handle": "MazhavilManorama", "role": "media"},
    {"name": "Surya TV",             "handle": "suryatv",          "role": "media"},
    {"name": "Zee Tamil",            "handle": "ZeeTamil",         "role": "media"},
    {"name": "Kalaignar TV",         "handle": "kalaignartv",      "role": "media"},
    # ── OTT Platforms ─────────────────────────────────────────────────────────
    {"name": "Netflix India",        "handle": "NetflixIndia",     "role": "ott"},
    {"name": "Prime Video India",    "handle": "PrimeVideoIN",     "role": "ott"},
    {"name": "Disney+ Hotstar",      "handle": "HotstarTweets",    "role": "ott"},
    {"name": "SonyLIV",              "handle": "SonyLIV",          "role": "ott"},
    {"name": "ZEE5 India",           "handle": "ZEE5India",        "role": "ott"},
    {"name": "Aha Video",            "handle": "ahavideoIN",       "role": "ott"},
    {"name": "Sun NXT",              "handle": "SunNXT",           "role": "ott"},
    {"name": "Manorama Online",      "handle": "ManoramaOnline",   "role": "ott"},
    {"name": "Mubi India",           "handle": "MUBIIndia",        "role": "ott"},
    {"name": "Neestream",            "handle": "Neestream",        "role": "ott"},
]

# Quick lookups
BY_HANDLE: dict[str, dict]        = {a["handle"].lower(): a for a in ACTORS}
BY_DB_NAME: dict[str, dict]       = {a["db_name"].lower(): a for a in ACTORS}
ALL_HANDLES: list[str]            = [a["handle"] for a in ACTORS]

SIGNALS_BY_HANDLE: dict[str, dict] = {s["handle"].lower(): s for s in SIGNAL_ACCOUNTS}
ALL_SIGNAL_HANDLES: list[str]      = [s["handle"] for s in SIGNAL_ACCOUNTS]
